version: '3'
services:
  client:
    build: ./client
    container_name: client
    restart: unless-stopped
    networks:
      - app-network

  server:
    build: ./server
    container_name: server
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "8080:8080"

  web:
    build: ./web
    container_name: web
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "3000:80"

networks:
  app-network:
    driver: bridge
