version: '3'
services:
  backend:
    build: ./server
    restart: unless-stopped
    networks:
      - fileoptimizer-network
    ports:
      - "5001:5000"
  frontend:
    build: ./web
    restart: unless-stopped
    networks:
      - fileoptimizer-network
    ports:
      - "3001:3000"
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    networks:
      - fileoptimizer-network

networks:
  fileoptimizer-network :
    driver: bridge
